run:
  timeout: 5m
  tests: true
  build-tags:
    - integration

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gosec
    - gocyclo
    - dupl
    - misspell
    - lll
    - goconst
    - gocritic
    - gocognit
    - godox
    - bodyclose
    - noctx
    - stylecheck
    - exportloopref
    - whitespace
    - unparam
    - prealloc
    - predeclared
    - nilerr
    - exhaustive
    - sqlclosecheck
    - nolintlint
    - gofumpt
    - gci
    - godot
    - nlreturn
    - tparallel
    - thelper
    - forbidigo
    - cyclop
    - paralleltest

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/fredcamaral/gomcp-sdk
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 120
  gocognit:
    min-complexity: 20
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  nolintlint:
    allow-unused: false
    require-explanation: true
    require-specific: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/fredcamaral/gomcp-sdk)
  godot:
    scope: all
  cyclop:
    max-complexity: 15
    package-average: 10
    skip-tests: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - path: testutil/
      linters:
        - gosec
    - path: examples/
      linters:
        - gocyclo
        - gocognit
        - godox

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0